#!/bin/bash
set -x
# convert and rotate the images in a directory
# panorotate <targdir> 

if [[ $# -ne 1 ]]; then
  echo "illegal number of parameters"
  exit -1;
fi

targdir=$1
#rotate=$2

#first we convert all .RW2 files to PPM files
time (cd $targdir; for v in *.RW2; do dcraw $v; done )
#now we find out if we need to rotate 90 or -90
#first get the imagefile to check
imgfile=`(cd $targdir; ls *.ppm | sort | head -1)`
echo $imgfile

rotate=1
result=`python3.6 find_rig.py $targdir/$imgfile`
if [ "$result" == "True" ]; then
   rotate=0;
fi

#now we use imagemagick to do the rotation.
#time (cd $targdir; magick mogrify -format png -rotate $rotate *.ppm )
time (cd $targdir; for v in *.ppm; do python3.6 /home/STEVENCUTCHIN/builds/openpipe/panosort/rotate_image_cpu.py ${v} $rotate ${v%.ppm}.png ; done)

#now we delete the ppm files
(cd $targdir; rm *.ppm )
